Fixed issue with special characters not being escaped in the local path when pushing
Malinskiy/adam pull request #78
Opened 2022-03-21 03:56 UTC by evant

When creating a directory on the device it was passing `path.name`
directly to `mkdir` without escaping it. This causes issues with
characters that are interpreted specially with the shell.

2022-03-28 06:28 UTC, Malinskiy requested changes

2022-03-28 06:28 UTC, Malinskiy commented on adam/src/main/kotlin/com/malinskiy/adam/request/sync/PushRequest.kt
> +        execute(ShellCommandRequest("mkdir -p ${escape(destination)}"), serial)
Do you mind using `bashEscape` that is available as an extension on `List<String>`? I don't want to reimplement escaping per request

2022-03-28 15:02 UTC, evant commented on adam/src/main/kotlin/com/malinskiy/adam/extension/List.kt
> +fun List<String>.bashEscape() = "'" + joinToString(" ") { it.replace("'", "'\\''") } + "'"
Just escaping the quote inside single quotes doesn't do what you want, you need to end the single quotes, insert it, and start single quotes again.

2022-03-30 00:44 UTC, merged

2022-03-30 00:45 UTC, Malinskiy commented
Awesome work @evant. Thanks a lot!